"""
Synthetic electricity demand data generator.

This module generates realistic synthetic electricity demand data for testing
and development when real PJM data is not available. The synthetic data includes:
- Daily and annual seasonality patterns
- Weekly patterns (weekday vs weekend)
- Long-term trend
- Holiday effects
- Temperature/weather effects
- Random noise

IMPORTANT: Data generated by this module is SYNTHETIC and should be clearly
labeled as such in any analysis or reporting.
"""

from datetime import datetime
from typing import Any

import holidays
import numpy as np
import pandas as pd

from forecast_service.utils.logging import get_logger

logger = get_logger(__name__)


class SyntheticDataGenerator:
    """
    Generate synthetic electricity demand data with realistic patterns.

    The generator creates hourly load data with:
    - Base load level (~30,000 MW, typical for PJM-scale utilities)
    - Daily pattern (peaks in morning/evening, trough at night)
    - Annual seasonality (higher in summer/winter for HVAC)
    - Weekly pattern (lower on weekends)
    - Holiday effects (reduced commercial/industrial load)
    - Temperature effects (U-shaped relationship with load)
    - Random noise

    Attributes:
        seed: Random seed for reproducibility.
        base_load: Base load level in MW.
    """

    # Label to identify synthetic data
    SYNTHETIC_LABEL = "SYNTHETIC"

    def __init__(
        self,
        seed: int = 42,
        base_load: float = 32000.0,
        noise_std: float = 500.0,
    ) -> None:
        """
        Initialize the synthetic data generator.

        Args:
            seed: Random seed for reproducibility.
            base_load: Base load level in MW.
            noise_std: Standard deviation of random noise.
        """
        self.seed = seed
        self.base_load = base_load
        self.noise_std = noise_std
        self.rng = np.random.default_rng(seed)
        self._us_holidays = holidays.US()

        logger.info(
            "Initialized SyntheticDataGenerator",
            seed=seed,
            base_load=base_load,
            data_type=self.SYNTHETIC_LABEL,
        )

    def generate(
        self,
        start_date: str | datetime = "2015-01-01",
        end_date: str | datetime = "2018-12-31",
        include_temperature: bool = True,
    ) -> pd.DataFrame:
        """
        Generate synthetic electricity demand data.

        Args:
            start_date: Start date for generated data.
            end_date: End date for generated data.
            include_temperature: Whether to include synthetic temperature data.

        Returns:
            DataFrame with datetime index, 'load_mw' column, and optionally
            'temperature_f' column. Contains metadata attribute marking it as synthetic.
        """
        logger.info(
            "Generating synthetic data",
            start=str(start_date),
            end=str(end_date),
            data_type=self.SYNTHETIC_LABEL,
        )

        # Create hourly datetime index
        index = pd.date_range(start=start_date, end=end_date, freq="h")
        n_hours = len(index)

        # Generate components
        daily_pattern = self._generate_daily_pattern(index)
        annual_pattern = self._generate_annual_pattern(index)
        weekly_pattern = self._generate_weekly_pattern(index)
        trend = self._generate_trend(n_hours)
        holiday_effect = self._generate_holiday_effect(index)
        noise = self.rng.normal(0, self.noise_std, n_hours)

        # Generate temperature (used for weather effects)
        temperature = self._generate_temperature(index)
        weather_effect = self._generate_weather_effect(temperature)

        # Combine all components
        load = (
            self.base_load
            + daily_pattern
            + annual_pattern
            + weekly_pattern
            + trend
            + holiday_effect
            + weather_effect
            + noise
        )

        # Ensure non-negative load
        load = np.maximum(load, self.base_load * 0.3)

        # Create DataFrame
        data: dict[str, Any] = {"load_mw": load}
        if include_temperature:
            data["temperature_f"] = temperature

        df = pd.DataFrame(data, index=index)
        df.index.name = "datetime"

        # Add metadata to identify as synthetic
        df.attrs["data_source"] = self.SYNTHETIC_LABEL
        df.attrs["generator_seed"] = self.seed

        logger.info(
            "Generated synthetic data",
            rows=len(df),
            mean_load=float(df["load_mw"].mean()),
            data_type=self.SYNTHETIC_LABEL,
        )

        return df

    def _generate_daily_pattern(self, index: pd.DatetimeIndex) -> np.ndarray:
        """
        Generate daily load pattern.

        Peak hours: 8-9 AM and 6-8 PM
        Trough hours: 2-5 AM
        """
        hours = index.hour.values

        # Morning peak around 8 AM
        morning_peak = 3000 * np.exp(-0.5 * ((hours - 8) / 2) ** 2)

        # Evening peak around 7 PM
        evening_peak = 4000 * np.exp(-0.5 * ((hours - 19) / 2.5) ** 2)

        # Night trough
        night_reduction = -2000 * np.exp(-0.5 * ((hours - 3) / 3) ** 2)

        return morning_peak + evening_peak + night_reduction

    def _generate_annual_pattern(self, index: pd.DatetimeIndex) -> np.ndarray:
        """
        Generate annual seasonality pattern.

        Higher load in summer (AC) and winter (heating).
        Lower load in spring/fall (mild weather).
        """
        day_of_year = index.dayofyear.values

        # Summer peak (around day 200, mid-July)
        summer_effect = 5000 * np.exp(-0.5 * ((day_of_year - 200) / 40) ** 2)

        # Winter peak (around day 15 and 350, January and December)
        winter_effect = 3000 * (
            np.exp(-0.5 * ((day_of_year - 15) / 30) ** 2)
            + np.exp(-0.5 * ((day_of_year - 350) / 30) ** 2)
        )

        # Spring/fall reduction
        spring_fall = -2000 * (
            np.exp(-0.5 * ((day_of_year - 100) / 25) ** 2)  # April
            + np.exp(-0.5 * ((day_of_year - 280) / 25) ** 2)  # October
        )

        return summer_effect + winter_effect + spring_fall

    def _generate_weekly_pattern(self, index: pd.DatetimeIndex) -> np.ndarray:
        """
        Generate weekly pattern.

        Lower load on weekends due to reduced commercial/industrial activity.
        """
        day_of_week = index.dayofweek.values

        # Weekend reduction (Saturday=5, Sunday=6)
        weekend_effect = np.where(day_of_week >= 5, -3000, 0)

        # Friday afternoon slightly lower
        friday_effect = np.where(
            (day_of_week == 4) & (index.hour.values >= 15), -500, 0
        )

        # Monday morning ramp-up (slightly lower early Monday)
        monday_effect = np.where(
            (day_of_week == 0) & (index.hour.values < 10), -800, 0
        )

        return weekend_effect + friday_effect + monday_effect

    def _generate_trend(self, n_hours: int) -> np.ndarray:
        """
        Generate long-term trend.

        Slight upward trend reflecting population/economic growth,
        partially offset by efficiency improvements.
        """
        # Slight upward trend (~1% per year)
        years = n_hours / (24 * 365)
        trend = np.linspace(0, years * 0.01 * self.base_load, n_hours)

        # Add some slow variation (multi-year cycles)
        cycle = 500 * np.sin(2 * np.pi * np.arange(n_hours) / (24 * 365 * 3))

        return trend + cycle

    def _generate_holiday_effect(self, index: pd.DatetimeIndex) -> np.ndarray:
        """
        Generate holiday effects.

        Reduced load on holidays due to commercial/industrial closures.
        """
        effect = np.zeros(len(index))

        for i, dt in enumerate(index):
            date = dt.date()
            if date in self._us_holidays:
                # Larger reduction during business hours
                if 8 <= dt.hour <= 18:
                    effect[i] = -4000
                else:
                    effect[i] = -1500

            # Day after major holidays (partial recovery)
            prev_date = pd.Timestamp(date) - pd.Timedelta(days=1)
            if prev_date.date() in self._us_holidays:
                effect[i] += -500

        return effect

    def _generate_temperature(self, index: pd.DatetimeIndex) -> np.ndarray:
        """
        Generate synthetic temperature data.

        Temperature follows:
        - Annual cycle (cold winter, hot summer)
        - Daily cycle (cooler at night)
        - Random weather variation
        """
        n = len(index)
        day_of_year = index.dayofyear.values
        hour = index.hour.values

        # Annual temperature cycle (peak in late July)
        annual = 50 + 30 * np.sin(2 * np.pi * (day_of_year - 80) / 365)

        # Daily temperature cycle
        daily = 8 * np.sin(2 * np.pi * (hour - 6) / 24)

        # Weather fronts (multi-day variation)
        weather_period = 24 * 5  # 5-day weather cycles
        weather = 10 * np.sin(2 * np.pi * np.arange(n) / weather_period)
        weather += self.rng.normal(0, 3, n)  # Day-to-day variation

        return annual + daily + weather

    def _generate_weather_effect(self, temperature: np.ndarray) -> np.ndarray:
        """
        Generate weather effect on load.

        U-shaped relationship: load increases for both cold and hot temperatures
        due to heating and cooling needs. Minimum load around 65°F.
        """
        # Optimal temperature (minimal HVAC load)
        optimal_temp = 65

        # Heating effect (cold weather)
        heating = np.where(
            temperature < optimal_temp,
            100 * (optimal_temp - temperature),
            0
        )

        # Cooling effect (hot weather, stronger than heating)
        cooling = np.where(
            temperature > optimal_temp,
            150 * (temperature - optimal_temp),
            0
        )

        return heating + cooling


def generate_synthetic_data(
    start_date: str = "2015-01-01",
    end_date: str = "2018-12-31",
    seed: int = 42,
    include_temperature: bool = True,
) -> pd.DataFrame:
    """
    Convenience function to generate synthetic electricity demand data.

    IMPORTANT: This generates SYNTHETIC data for testing purposes.
    Not to be used as a substitute for real data in production analysis.

    Args:
        start_date: Start date for generated data.
        end_date: End date for generated data.
        seed: Random seed for reproducibility.
        include_temperature: Whether to include temperature data.

    Returns:
        DataFrame with synthetic electricity demand data.
    """
    generator = SyntheticDataGenerator(seed=seed)
    return generator.generate(
        start_date=start_date,
        end_date=end_date,
        include_temperature=include_temperature,
    )


def is_synthetic(df: pd.DataFrame) -> bool:
    """Check if a DataFrame contains synthetic data."""
    return df.attrs.get("data_source") == SyntheticDataGenerator.SYNTHETIC_LABEL
